### ISSUE TITLE
Application / Zone To-Do

### ISSUE THREAD

**Issue by AdamDenoon** [decodico/disruptivestrong#2]
- [x] Make panel for re-approving members (who changed desired zips, either by personal choice or because zip was not approved initially)
- [x] Send approved/denied zips in confirmation/notification emails
- [x] Add subdomains to email URLs
- [x] Validate zips on all entry forms
- [x] Ensure uniqueness of zips
- [x] Set up payments for all subscriptions/purchases to fork appropriately to zip owners
